/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CSApackage;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author rod
 */
public class RunExperimentDlg extends javax.swing.JDialog {
  
//  Font font = new Font("monospaced",Font.PLAIN,36);
  
MainCSA_demoPanel m_Controller = null;

  /**
   * Creates new form RunExperimentDlg
   */
  public RunExperimentDlg(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    
    m_Controller = ((CSAdemo)parent).getMain_CSA_panel();
    
    initComponents();
    
    
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    expSettings = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    maxV = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    maxVDelta = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    numSamples = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    minCrosstalk = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    maxCrosstalk = new javax.swing.JTextField();
    IP = new javax.swing.JLabel();
    IP_val = new javax.swing.JTextField();
    Ecc = new javax.swing.JLabel();
    Ecc_val = new javax.swing.JTextField();
    outputFileChooser = new javax.swing.JFileChooser();
    runExp = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    abbrevOutputChkBx = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Choose Output File for Experiment Results");
    setFont(new java.awt.Font("Adobe Arabic", 0, 18)); // NOI18N
    setLocation(new java.awt.Point(0, 0));
    getContentPane().setLayout(new java.awt.GridBagLayout());

    java.awt.GridBagLayout expSettingsLayout = new java.awt.GridBagLayout();
    expSettingsLayout.columnWidths = new int[] {0, 5, 0, 5, 0};
    expSettingsLayout.rowHeights = new int[] {0, 5, 0, 5, 0};
    expSettings.setLayout(expSettingsLayout);

    jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel5.setText("Max V");
    jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    expSettings.add(jLabel5, gridBagConstraints);

    maxV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    maxV.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
    maxV.setText("1.0");
    maxV.setMinimumSize(new java.awt.Dimension(60, 28));
    maxV.setPreferredSize(new java.awt.Dimension(80, 26));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
    expSettings.add(maxV, gridBagConstraints);

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setText("Max V Delta");
    jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    expSettings.add(jLabel1, gridBagConstraints);

    maxVDelta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    maxVDelta.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
    maxVDelta.setText("0.1");
    maxVDelta.setMinimumSize(new java.awt.Dimension(60, 28));
    maxVDelta.setPreferredSize(new java.awt.Dimension(80, 26));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
    expSettings.add(maxVDelta, gridBagConstraints);

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel2.setText("Num Samples");
    jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
    expSettings.add(jLabel2, gridBagConstraints);

    numSamples.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    numSamples.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
    numSamples.setText("3");
    numSamples.setMinimumSize(new java.awt.Dimension(60, 28));
    numSamples.setPreferredSize(new java.awt.Dimension(80, 26));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 0);
    expSettings.add(numSamples, gridBagConstraints);

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Min Crosstalk");
    jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    expSettings.add(jLabel3, gridBagConstraints);

    minCrosstalk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    minCrosstalk.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
    minCrosstalk.setText("0.10");
    minCrosstalk.setMinimumSize(new java.awt.Dimension(60, 28));
    minCrosstalk.setPreferredSize(new java.awt.Dimension(80, 26));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
    expSettings.add(minCrosstalk, gridBagConstraints);

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Max Crosstalk");
    jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    expSettings.add(jLabel4, gridBagConstraints);

    maxCrosstalk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    maxCrosstalk.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
    maxCrosstalk.setText("0.20");
    maxCrosstalk.setMinimumSize(new java.awt.Dimension(60, 28));
    maxCrosstalk.setPreferredSize(new java.awt.Dimension(80, 26));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
    expSettings.add(maxCrosstalk, gridBagConstraints);

    IP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    IP.setText("IP");
    IP.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    expSettings.add(IP, gridBagConstraints);

    IP_val.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    IP_val.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
    IP_val.setText("50");
    IP_val.setMinimumSize(new java.awt.Dimension(60, 28));
    IP_val.setPreferredSize(new java.awt.Dimension(80, 26));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 0);
    expSettings.add(IP_val, gridBagConstraints);

    Ecc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    Ecc.setText("Eccentricity");
    Ecc.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    expSettings.add(Ecc, gridBagConstraints);

    Ecc_val.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    Ecc_val.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
    Ecc_val.setText("15");
    Ecc_val.setMinimumSize(new java.awt.Dimension(60, 28));
    Ecc_val.setPreferredSize(new java.awt.Dimension(80, 26));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
    expSettings.add(Ecc_val, gridBagConstraints);

    getContentPane().add(expSettings, new java.awt.GridBagConstraints());

    outputFileChooser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weighty = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
    getContentPane().add(outputFileChooser, gridBagConstraints);

    runExp.setBackground(new java.awt.Color(255, 204, 153));
    runExp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    runExp.setText("Run Experiment");
    runExp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        runExpActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.ipadx = 3;
    gridBagConstraints.ipady = 3;
    gridBagConstraints.insets = new java.awt.Insets(16, 6, 16, 6);
    getContentPane().add(runExp, gridBagConstraints);

    jTextArea1.setColumns(20);
    jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(jScrollPane1, gridBagConstraints);

    abbrevOutputChkBx.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    abbrevOutputChkBx.setText("Abbreviated Output");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    getContentPane().add(abbrevOutputChkBx, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void runExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runExpActionPerformed
    
    // We will get settings of parameters from GUI controls.  
    // Outer loop will iterate over max v values from 1.0 down to a lower limit by decrements equal to max V delta.
    // Inner loop will iterate over number x of specified samples.  Basically, this is just number of times to hit the "Generate New Sample" button.
    // We'll report the ave of the Expected Accuracy and of its Std. Dev, over those x samples.
    // We write several vals: all the params, max V, ave. expecte acc., and ave std. dev. of expected acc., on each line of output file.
    
    double max_V = Double.parseDouble(this.maxV.getText());
//    double max_V_low_lim = (double)m_Controller.getMaxCrosstalkLimitValue() / 100;
    
    double max_V_low_lim = Double.parseDouble(this.maxCrosstalk.getText());
    m_Controller.getTheApp().theMac.setEccentricity(Integer.parseInt(this.Ecc_val.getText()));
    m_Controller.getTheApp().theMac.setHorizInflectionLocation(Integer.parseInt(this.IP_val.getText()));
    m_Controller.getTheApp().theMac.SetCrossTalkLowLim(Float.parseFloat(this.minCrosstalk.getText()));
    m_Controller.getTheApp().theMac.SetCrossTalkHighLim(Float.parseFloat(this.maxCrosstalk.getText()));
    
    m_Controller.updateOtherPanelsConsistently();
    m_Controller.updateSliders(
            Integer.parseInt(this.IP_val.getText()), 
            Integer.parseInt(this.Ecc_val.getText()),
            Float.parseFloat(this.minCrosstalk.getText()),
            Float.parseFloat(this.maxCrosstalk.getText()));
    
    double max_V_delta = Double.parseDouble(maxVDelta.getText());
    int numSamples = Integer.parseInt(this.numSamples.getText());
    double single_exp_acc_res = 0;
    double single_std_dev_res = 0;
      
    this.jTextArea1.append(String.format("\n *** EXP. max V ranges from %3.2f to %3.2f in %3.2f deltas.  %2d samples for each max V value ***\n", max_V, max_V_low_lim, max_V_delta, numSamples));
    this.jTextArea1.append(String.format("\n *** Params: Q: %2d  K: %2d  Eccentricity: %2d  Inflection: %2d  Eta Mult: %3d  Gamma: %2d  Crosstalk: [%3.2f, %3.2f] ***\n\n", 
            m_Controller.getTheApp().theMac.Q , m_Controller.getTheApp().theMac.K, 
            (int) m_Controller.getTheApp().theMac.getEccentricity(), m_Controller.getTheApp().theMac.getHorizInflectionLocation(),
            m_Controller.getTheApp().theMac.getV_to_mu_Multiplier(), (int) m_Controller.getTheApp().theMac.getGamma(),
            m_Controller.getTheApp().theMac.GetCrossTalkLowLim(), m_Controller.getTheApp().theMac.GetCrossTalkHighLim()
    ));
    
    while (max_V >= max_V_low_lim)
    {
      double aveExpAcc = 0;
      double aveStdDev = 0;
      
      m_Controller.getTheApp().theMac.SetWinner_V_Val((float)max_V);
                 
      //// Optionally update sigmoid parameters as function of G and/or crosstalk
      
      // Should have option to either set IP and ecc,
      //   - as fn of G
      //   - as fn of crosstalk
      //   - as fn of G and crosstalk
      // and all of these possible dependencies should be either
      //   - computed using hardcoded fns, or
      //   - gotten from tables specfied in files.
      
      
      
//      int val = (int) (-0.2f * m_Controller.getTheApp().theMac.GetWinner_V_Val() ) + 30;
//      m_Controller.getTheApp().theMac.setEccentricity(val);
              
      // run exp specified num of times
      for (int x = 0; x < numSamples; x++)
      {
        m_Controller.getTheApp().theMac.create_V_Distributions(true, true);
        m_Controller.getTheApp().theMac.updateDependentDistributions();
        m_Controller.getTheApp().theMac.chooseCodeAndComputeAccuracies();
        m_Controller.updateStatsControls();
        
        //should wait here a little bit.
        
        single_exp_acc_res = m_Controller.getTheApp().theMac.getExpectedAccuracy();
//        single_exp_acc_res = m_Controller.getTheApp().theMac.accuracy;
        single_std_dev_res = m_Controller.getTheApp().theMac.getStdDevExpectedAccuracy();
        
//        single_exp_acc_res = Double.parseDouble(m_Controller.expectedAccuracy.getText());
//        single_std_dev_res = Double.parseDouble(m_Controller.stdDevAccuracy.getText());
        
        if ( ! this.abbrevOutputChkBx.isSelected())
        {
          this.jTextArea1.append(String.format("                      max V: %3.2f  exp. accuracy: %3.2f   std. Dev.: %3.2f\n", max_V, single_exp_acc_res, single_std_dev_res));
        }
        
        aveExpAcc += single_exp_acc_res;
        aveStdDev += single_std_dev_res;        
      }
      
      aveExpAcc /= numSamples;
      aveStdDev /= numSamples;
              
      // write values to outputfile
      
      if ( ! this.abbrevOutputChkBx.isSelected())
      {
        this.jTextArea1.append(String.format(" AVE OF %2d SAMPLES    max V: %3.2f  exp. accuracy: %3.2f   std. Dev.: %3.2f\n\n", numSamples, max_V, aveExpAcc, aveStdDev));
      }
      else
      {
        this.jTextArea1.append(String.format(" G: %3.2f  exp. int.: %3.2f   std. Dev.: %3.2f\n", max_V, aveExpAcc, aveStdDev));
      }
          
//      this.jTextArea1.append(String.format("------------------------------------------------------------------------------\n\n"));
      
      max_V -= max_V_delta;
      
      //NOTE:  SHOULD WE update GUI controls to be in synced with automated experiments....Nahhh...Rod 4-1-19
//      m_Controller.updateStateOfGUI();
      
    }
  }//GEN-LAST:event_runExpActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(RunExperimentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(RunExperimentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(RunExperimentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(RunExperimentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        RunExperimentDlg dialog = new RunExperimentDlg(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Ecc;
  protected javax.swing.JTextField Ecc_val;
  private javax.swing.JLabel IP;
  protected javax.swing.JTextField IP_val;
  private javax.swing.JCheckBox abbrevOutputChkBx;
  private javax.swing.JPanel expSettings;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  protected javax.swing.JTextField maxCrosstalk;
  protected javax.swing.JTextField maxV;
  protected javax.swing.JTextField maxVDelta;
  protected javax.swing.JTextField minCrosstalk;
  protected javax.swing.JTextField numSamples;
  protected javax.swing.JFileChooser outputFileChooser;
  private javax.swing.JButton runExp;
  // End of variables declaration//GEN-END:variables
}
